### ISSUE TITLE
Using a raw import link will not work on BD

### ISSUE THREAD

**Issue by TheCommieAxolotl** [x86atron/Oreocord#1]
You appear to be using a github raw url as the [import url for your bd theme file](https://github.com/x86atron/Oreocord/blob/main/Oreocord.theme.css#L9). This will not work as githubraw does not set the proper content type and cannot be used as an import. The fix for this is to set up github pages to host this repo and serve the pages url instead. See the [BD docs](https://docs.betterdiscord.app/themes/intermediate/remote#your-theme) on how to do this.

**Comment by x86atron** [comment]
Will importing the stylesheet directly from my website work?

**Comment by TheCommieAxolotl** [comment]
It is recommended to use github pages as some clients do not enable CSP bypasses for all sites.

**Comment by x86atron** [comment]
I think I resolved the issue with the `@import` link. [Here it is.](https://x86atron.github.io/Oreocord/Oreocord.css)
